language: python

python:
    - 3.6

os:
    - linux

install:
    - pip install -r requirements.txt

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm; fi

script:
    - nosetests
